import type { MarkdownConfig, MarkdownElementType, MarkdownStyle } from './types';

export const defaultMarkdownStyles: Record<MarkdownElementType, MarkdownStyle> = {
  heading1: {
    fontSize: 36,
    fontWeight: 700,
    letterSpacing: 2,
    inkColor: '#2a1f14',
    lineHeight: 1.4,
    marginTop: 12,
    marginBottom: 20,
    jitterAmount: 0.3,
  },
  heading2: {
    fontSize: 30,
    fontWeight: 600,
    letterSpacing: 1,
    inkColor: '#3a2e1f',
    lineHeight: 1.4,
    marginTop: 10,
    marginBottom: 16,
    jitterAmount: 0.35,
  },
  heading3: {
    fontSize: 26,
    fontWeight: 600,
    letterSpacing: 0.5,
    inkColor: '#3a2e1f',
    lineHeight: 1.5,
    marginTop: 8,
    marginBottom: 12,
    jitterAmount: 0.4,
  },
  paragraph: {
    fontSize: 24,
    fontWeight: 400,
    letterSpacing: 0,
    inkColor: '#3a2e1f',
    lineHeight: 1.8,
    marginTop: 0,
    marginBottom: 16,
    jitterAmount: 0.55,
  },
  blockquote: {
    fontSize: 22,
    fontWeight: 400,
    letterSpacing: 0,
    inkColor: '#5a4a3a',
    lineHeight: 1.9,
    marginTop: 8,
    marginBottom: 16,
    paddingLeft: 24,
    jitterAmount: 0.5,
    borderLeft: {
      width: 4,
      color: '#c9a67a',
      offset: 12,
    },
    background: {
      color: 'rgba(201, 166, 122, 0.12)',
      padding: 12,
      borderRadius: 4,
    },
  },
  unorderedList: {
    fontSize: 24,
    fontWeight: 400,
    letterSpacing: 0,
    inkColor: '#3a2e1f',
    lineHeight: 1.8,
    marginTop: 4,
    marginBottom: 12,
    jitterAmount: 0.55,
    listStyle: {
      type: 'bullet',
      indent: 28,
    },
  },
  orderedList: {
    fontSize: 24,
    fontWeight: 400,
    letterSpacing: 0,
    inkColor: '#3a2e1f',
    lineHeight: 1.8,
    marginTop: 4,
    marginBottom: 12,
    jitterAmount: 0.55,
    listStyle: {
      type: 'number',
      indent: 32,
    },
  },
  listItem: {
    fontSize: 24,
    fontWeight: 400,
    letterSpacing: 0,
    inkColor: '#3a2e1f',
    lineHeight: 1.8,
    marginTop: 0,
    marginBottom: 4,
    jitterAmount: 0.55,
  },
  bold: {
    fontSize: 24,
    fontWeight: 700,
    letterSpacing: 0,
    inkColor: '#2a1f14',
    lineHeight: 1.8,
    marginTop: 0,
    marginBottom: 0,
    jitterAmount: 0.5,
  },
  italic: {
    fontSize: 24,
    fontWeight: 400,
    letterSpacing: 0,
    inkColor: '#3a2e1f',
    lineHeight: 1.8,
    marginTop: 0,
    marginBottom: 0,
    jitterAmount: 0.6,
  },
  boldItalic: {
    fontSize: 24,
    fontWeight: 700,
    letterSpacing: 0,
    inkColor: '#2a1f14',
    lineHeight: 1.8,
    marginTop: 0,
    marginBottom: 0,
    jitterAmount: 0.55,
  },
  strikethrough: {
    fontSize: 24,
    fontWeight: 400,
    letterSpacing: 0,
    inkColor: '#8a7a6a',
    lineHeight: 1.8,
    marginTop: 0,
    marginBottom: 0,
    jitterAmount: 0.55,
  },
  code: {
    fontSize: 22,
    fontWeight: 400,
    letterSpacing: 0,
    inkColor: '#c9542c',
    lineHeight: 1.8,
    marginTop: 0,
    marginBottom: 0,
    jitterAmount: 0.3,
  },
  link: {
    fontSize: 24,
    fontWeight: 400,
    letterSpacing: 0,
    inkColor: '#2563eb',
    lineHeight: 1.8,
    marginTop: 0,
    marginBottom: 0,
    jitterAmount: 0.5,
  },
  text: {
    fontSize: 24,
    fontWeight: 400,
    letterSpacing: 0,
    inkColor: '#3a2e1f',
    lineHeight: 1.8,
    marginTop: 0,
    marginBottom: 0,
    jitterAmount: 0.55,
  },
};

export const defaultMarkdownConfig: MarkdownConfig = {
  enabled: true,
  styles: defaultMarkdownStyles,
};

export function mergeMarkdownStyle(
  baseStyle: MarkdownStyle,
  overrides: Partial<MarkdownStyle>
): MarkdownStyle {
  return {
    ...baseStyle,
    ...overrides,
  };
}
